dynamic api_machine_status = {
  "data": [
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "9",
      "machine_name": "A50-1 Assembly front face",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "10",
      "machine_name": "A60",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "19",
      "machine_name": "ATP-RF-OTA 2",
      "machine_type": "RB OTA_FC",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "14",
      "machine_name": "M1",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "10",
      "machine_name": "A50-2 Ultrasonic plastic welding",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "16",
      "machine_name": "OTA/Final check Test RF-OTA & final check 1",
      "machine_type": "RB OTA_FC",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "11",
      "machine_name": "A70",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "16",
      "machine_name": "A90-2",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "MINI ROUTER",
      "location": "22",
      "machine_name": "M2",
      "machine_type": "XY Machine",
      "status": "OFF",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "3",
      "machine_name": "MAY LAT BAN",
      "machine_type": "Lật Bản",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "13",
      "machine_name": "A60-2 Rear housing Laser Etch",
      "machine_type": "RB Lazer",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "4",
      "machine_name": "A10-1 Check Wifi housing input into JIG",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "6",
      "machine_name": "A20/AOI1 Stick vent to housing Press & AOI",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "1",
      "machine_name": "SMA PCBA-RF-WIFI",
      "machine_type": "RB PCBA",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "15",
      "machine_name": "A90-1",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "5",
      "machine_name": "A20",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "2",
      "machine_name": "PCBA-RF-WIFI & PCBA-POE 2",
      "machine_type": "RB PCBA",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "7",
      "machine_name": "A30 Assembly PCBA to Rear housing",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "14",
      "machine_name": "OCR Check content, wrong, missing",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "18",
      "machine_name": "OQC Sampling function test 10%",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "19",
      "machine_name": "M2 Unlock JIG & Output",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "13",
      "machine_name": "A80",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "6",
      "machine_name": "A30-1",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "12",
      "machine_name": "A60-1 Laser Front Face logo",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "1",
      "machine_name": "PCBA-RF-WIFI & PCBA-POE 1",
      "machine_type": "RB PCBA",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "2",
      "machine_name": "SMA PCBA-RF-WIFI",
      "machine_type": "RB PCBA",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "21",
      "machine_name": "OQC",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "8",
      "machine_name": "A40",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "17",
      "machine_name": "OTA/Final check Test RF-OTA & final check 2",
      "machine_type": "RB OTA_FC",
      "status": "RUN",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "5",
      "machine_name": "A10-2 Stick HH lable",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "20",
      "machine_name": "ATP-RF-OTA 3",
      "machine_type": "RB OTA_FC",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "9",
      "machine_name": "A50",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "8",
      "machine_name": "A40 Assembly Heat spreader to Rear housing",
      "machine_type": "XY Machine",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "12",
      "machine_name": "AUTO-VI",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "17",
      "machine_name": "OCR",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "4",
      "machine_name": "A10",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "7",
      "machine_name": "A30-2",
      "machine_type": "XY Machine",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "3",
      "machine_name": "Reverse PCBA",
      "machine_type": "Lật Bản",
      "status": "RUN",
    },
    {
      "error_code": "L2002",
      "line": "MINI ROUTER",
      "location": "18",
      "machine_name": "ATP-RF-OTA 1",
      "machine_type": "RB OTA_FC",
      "status": "CUT",
    },
    {
      "error_code": "",
      "line": "GEN3_1",
      "location": "15",
      "machine_name": "A70 Alr Leakage Testing IP56 RATED",
      "machine_type": "RB Airleak",
      "status": "RUN",
    },
  ],
};

dynamic api_dashboard_error_example = {
  'data': [
    {'error_code': 'E0001', 'count': 12, 'percentage': 0.44},
    {'error_code': 'E0002', 'count': 229, 'percentage': 8.26},
    {'error_code': 'E0003', 'count': 27, 'percentage': 0.98},
    {'error_code': 'E0004', 'count': 157, 'percentage': 5.66},
    {'error_code': 'E0005', 'count': 17, 'percentage': 0.62},
    {'error_code': 'E0006', 'count': 21, 'percentage': 0.77},
    {'error_code': 'E0007', 'count': 419, 'percentage': 15.1},
    {'error_code': 'E0011', 'count': 1792, 'percentage': 64.54},
    {'error_code': 'E0013', 'count': 81, 'percentage': 2.9299999999999997},
    {'error_code': 'L2002', 'count': 21, 'percentage': 0.77},
    {'error_code': 'L2003', 'count': 1, 'percentage': 0.05},
  ],
};

dynamic getErrorDetail_example = {
  "data": [
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_id": 27,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra van, khí, đế van...",
      "used_count": 3,
    },
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_id": 27,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra cảm biến...",
      "used_count": 3,
    },
    {
      "cause": "Cảm biến xylanh không hoạt động",
      "error_id": 28,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra cảm biến hoặc từ trong xylanh...",
      "used_count": 2,
    },
  ],
};

dynamic getListConfirm_example = {
  "data": [
    {
      "error_code": "G0014",
      "error_name": "Gắp lỗi/Picking error",
      "error_type": "Gắp lỗi/Picking error",
      "id": 318,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4586,
      "start_time": "2025-07-15 08:44:11",
      "status": "ERROR",
    },
    {
      "error_code": "G0015",
      "error_name": "Rơi liệu/ Material drop",
      "error_type": "Rơi liệu/ Material drop",
      "id": 314,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4466,
      "start_time": "2025-07-15 10:44:13",
      "status": "ERROR",
    },
    {
      "error_code": "G0015",
      "error_name": "Rơi liệu/ Material drop",
      "error_type": "Rơi liệu/ Material drop",
      "id": 319,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4344,
      "start_time": "2025-07-15 12:46:13",
      "status": "ERROR",
    },
  ],
};
dynamic getErrorByCode_example = {
  "error_list": [
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_code": "G0012",
      "error_name": "Bất thường xylanh/Cylinder error",
      "id": 27,
      "solution": "Kiểm tra van, khí, đế van...",
    },
    {
      "cause": "Cảm biến xylanh không hoạt động",
      "error_code": "G0012",
      "error_name": "Bất thường xylanh/Cylinder error",
      "id": 28,
      "solution": "Kiểm tra cảm biến hoặc từ trong xylanh...",
    },
  ],
  "idconfirm": 14,
};
dynamic getViewMaintenance_monthly_example = {
  "history": [
    {
      "action_taken": "Thay dầu và lọc dầu",
      "content": "Kiểm tra dầu thủy lực",
      "created_at": "2025-07-26 11:47:53.140000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "MONTHLY",
      "no": 1,
      "tech_spec": "Dầu thủy lực không đục, nhiệt độ ổn định",
    },
    {
      "action_taken": "Thay dầu và lọc dầu",
      "content": "Kiểm tra dầu thủy lực",
      "created_at": "2025-07-26 11:09:17.427000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "MONTHLY",
      "no": 2,
      "tech_spec": "Dầu thủy lực không đục, nhiệt độ ổn định",
    },
  ],
  "machine_info": {
    "machine_name": "Gap VI Automatically visual inspecttion Gap",
  },
};
dynamic getViewMaintenance_weekly_example = {
  "history": [
    {
      "action_taken": "Thay đầu mạng",
      "content": "Kiểm tra PLC",
      "created_at": "2025-07-26 12:17:39.483000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "WEEKLY",
      "no": 1,
      "tech_spec": "Dây mạng oke, đầu mạng sắp hỏng ",
    },
  ],
  "machine_info": {
    "machine_name": "Gap VI Automatically visual inspecttion Gap",
  },
};
